/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladorPrincipal;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.JLabelAriel;
/**
 *
 * @author ari_0
 */
public class PanelPrincipal extends JPanelCustom {
    
    private DefaultTableModel tablaNotificaciones;
    private ControladorPrincipal controlador;
    private PanelAdPersonas panelPersonas;
    private PanelRepNueva panelRepNueva;
    private PanelAdVehiculos panelVehiculos;
    private PanelPlanillaNueva panelPlanillaNueva;
    private PanelVerPlanillas panelVerPlanillas;
    private PanelAdPagos panelAdPagos;
    
    public PanelPrincipal() {
        tablaNotificaciones = new DefaultTableModel(null, getColumnas()){
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
            return false;
            } 
        };

        initComponents();
        this.jTableNotificaciones.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 15));
        this.jTableNotificaciones.getColumnModel().getColumn(0).setMinWidth(140);
        this.jTableNotificaciones.getColumnModel().getColumn(0).setMaxWidth(160);
        this.jTableNotificaciones.getColumnModel().getColumn(1).setMinWidth(300);
        this.jTableNotificaciones.getColumnModel().getColumn(2).setMaxWidth(220);
        this.jTableNotificaciones.getColumnModel().getColumn(2).setMinWidth(180);
        controlador = ControladorPrincipal.getInstancia(); //De esta manera uso solo un controlador
        
        //Creando todos los paneles - al momento de pasarlos al controlador siempre es la misma instancia
        // --> Podemos controlar que no aparezcan más de una vez la misma instancia
        this.panelPersonas = new PanelAdPersonas();
        this.panelRepNueva = new PanelRepNueva();
        this.panelVehiculos = new PanelAdVehiculos();
        this.panelPlanillaNueva = new PanelPlanillaNueva();
        this.panelVerPlanillas = new PanelVerPlanillas(); 
        
        añadirNotifDePrueba();  //Para poder mostrar dos notificaciones de ejemplo a Leo
    }

    
    private String[] getColumnas() {
        String columna[] = new String[]{"Tipo Notif.", "Descripción", "Camión"};
        return columna;
    }
    
    private void añadirNotifDePrueba(){
        String datos[] = new String[3];  //Tipo, Descripción, Patente
        datos[0] = "Cobro";
        datos[1] = "Cheque 123456789 al portador ya puede ser depositado";
        datos[2] = "Scania 330";
        this.tablaNotificaciones.addRow(datos);
        //--------------------------//
        datos[0] = "Mantenimiento";
        datos[1] = "Cambio Aceite de motor y filtro";
        datos[2] = "Mercedes Benz 1114";
        this.tablaNotificaciones.addRow(datos);
        
        this.jTableNotificaciones.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdCamiones = new javax.swing.JButton();
        jButtonAdPersonas = new javax.swing.JButton();
        jButtonNuevaPlanilla = new javax.swing.JButton();
        jButtonVerReparaciones = new javax.swing.JButton();
        jButtonVerPlanillas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotificaciones = new javax.swing.JTable();
        jButtonAdPagos = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 533));

        jButtonAdCamiones.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonAdCamiones.setText("<html><p>Administar</p><p>Camiones</p></html>");
        jButtonAdCamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdCamionesActionPerformed(evt);
            }
        });

        jButtonAdPersonas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonAdPersonas.setText("<html><p>Administrar</p><p>&nbsp;Personas</p></html>");
        jButtonAdPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdPersonasActionPerformed(evt);
            }
        });

        jButtonNuevaPlanilla.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonNuevaPlanilla.setText("<html><p>Nueva</p><p>Planilla</p></html>");
        jButtonNuevaPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaPlanillaActionPerformed(evt);
            }
        });

        jButtonVerReparaciones.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonVerReparaciones.setText("<html><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ver</p><p>Reparaciones</p></html>");
        jButtonVerReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerReparacionesActionPerformed(evt);
            }
        });

        jButtonVerPlanillas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonVerPlanillas.setText("<html><p>&nbsp;&nbsp;&nbsp;&nbsp;Ver</p><p>Planillas</p></html>");
        jButtonVerPlanillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPlanillasActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTableNotificaciones.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        jTableNotificaciones.setModel(tablaNotificaciones);
        jScrollPane1.setViewportView(jTableNotificaciones);

        jButtonAdPagos.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButtonAdPagos.setText("<html><p>Administar</p><p>&nbsp;&nbsp;&nbsp;Pagos</p></html>");
        jButtonAdPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButtonAdCamiones, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButtonNuevaPlanilla, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButtonVerReparaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButtonVerPlanillas, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButtonAdPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdCamiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdPersonas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNuevaPlanilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerReparaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVerPlanillas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdPagos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaPlanillaActionPerformed
        this.panelPlanillaNueva = new PanelPlanillaNueva(); //Para que se acomoden los datos
        controlador.cambiarDePanel(this.panelPlanillaNueva, "Nueva Planilla");
    }//GEN-LAST:event_jButtonNuevaPlanillaActionPerformed

    private void jButtonAdCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdCamionesActionPerformed
        this.panelVehiculos = new PanelAdVehiculos();
        controlador.cambiarDePanel(this.panelVehiculos, "Administar Vehículos");
    }//GEN-LAST:event_jButtonAdCamionesActionPerformed

    private void jButtonVerReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerReparacionesActionPerformed
        this.panelRepNueva = new PanelRepNueva();
        controlador.cambiarDePanel(this.panelRepNueva, "Ver Reparaciones");
    }//GEN-LAST:event_jButtonVerReparacionesActionPerformed

    private void jButtonAdPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdPersonasActionPerformed
        this.panelPersonas = new PanelAdPersonas();
        controlador.cambiarDePanel(this.panelPersonas, "Administar Personas");
    }//GEN-LAST:event_jButtonAdPersonasActionPerformed

    private void jButtonVerPlanillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPlanillasActionPerformed
        this.panelVerPlanillas = new PanelVerPlanillas();
        controlador.cambiarDePanel(this.panelVerPlanillas, "Ver Planillas");
    }//GEN-LAST:event_jButtonVerPlanillasActionPerformed

    private void jButtonAdPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdPagosActionPerformed
        // Action Performed de botón "Administrar Pagos"
        this.panelAdPagos = new PanelAdPagos();
        this.controlador.cambiarDePanel(this.panelAdPagos, "Administrar Pagos");
    }//GEN-LAST:event_jButtonAdPagosActionPerformed

    public PanelAdPersonas getPanelPersonas() {
        return panelPersonas;
    }

    public void setPanelPersonas(PanelAdPersonas panelPersonas) {
        this.panelPersonas = panelPersonas;
    }

    public PanelRepNueva getPanelReparaciones() {
        return panelRepNueva;
    }

    public void setPanelReparaciones(PanelRepNueva panelReparaciones) {
        this.panelRepNueva = panelReparaciones;
    }

    public PanelAdVehiculos getPanelVehiculos() {
        return panelVehiculos;
    }

    public void setPanelVehiculos(PanelAdVehiculos panelVehiculos) {
        this.panelVehiculos = panelVehiculos;
    }

    public PanelPlanillaNueva getPanelPlanillaNueva() {
        return panelPlanillaNueva;
    }

    public void setPanelPlanillaNueva(PanelPlanillaNueva panelPlanillaNueva) {
        this.panelPlanillaNueva = panelPlanillaNueva;
    }

    public PanelVerPlanillas getPanelVerPlanillas() {
        return panelVerPlanillas;
    }

    public void setPanelVerPlanillas(PanelVerPlanillas panelVerPlanillas) {
        this.panelVerPlanillas = panelVerPlanillas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdCamiones;
    private javax.swing.JButton jButtonAdPagos;
    private javax.swing.JButton jButtonAdPersonas;
    private javax.swing.JButton jButtonNuevaPlanilla;
    private javax.swing.JButton jButtonVerPlanillas;
    private javax.swing.JButton jButtonVerReparaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNotificaciones;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean sePuedeCerrar() {
        JLabel label = new JLabelAriel(" ¿DESEA CERRAR EL PROGRAMA? ");
        int valor = JOptionPane.showConfirmDialog(panelPersonas, label, " ¡ATENCIÓN! ", JOptionPane.YES_NO_OPTION);
        return valor == JOptionPane.YES_OPTION; 
    }

    @Override
    public void onFocus() {
        //Tendrían que cargarse las notificaciones de la Tabla - Someday
    }
}
